[package]
name = "run_command"
version = "0.0.1"
edition = "2021"
authors = ["MoghTech"]
description = "standardized way to run shell commands with a compact api."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
